name: Tests

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.17
      - name: Checkout code
        uses: actions/checkout@v2
      - name: run tests
        run: make test
        if: env.GIT_DIFF
